### ISSUE TITLE
The 404 page apears complitely white

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#1017]
### Problem
- White screen: https://hunger.openfoodfacts.org//logos/search?barcode=4056489564430
- The logo per product view is broken
- @raphael0202 @alexfauquette

**Comment by alexfauquette** [comment]
It works if you replace the double `//` by a single `/`


```diff
- https://hunger.openfoodfacts.org//logos/search?barcode=4056489564430
+ https://hunger.openfoodfacts.org/logos/search?barcode=4056489564430
```

Technically speaking it's the 404 page that is broken

**Comment by alexfauquette** [comment]
From the error message in the console saying `require` is not defined I assume it comes from this lin: https://github.com/openfoodfacts/hunger-games/blob/master/src/pages/not-found/index.jsx/#L20

**Comment by teolemon** [comment]
got there from the "Annotate product logos" button https://hunger.openfoodfacts.org/questions @alexfauquette
