### ISSUE TITLE
Translate advanced info in user language

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#1059]
From https://openfoodfacts.slack.com/archives/CKTK52D1N/p1729979515559769

Could information on a product be translated in the user's language on Hunger Games? It would make it way easier to have the ingredients, categories, etc. translated when the translations are available.
Link to the product: https://world-fr.openfoodfacts.org/cgi/product.pl?type=edit&code=4250241204170

![Image](https://github.com/user-attachments/assets/81414de3-45b4-4443-8d05-881662eebe70)

Fields impacted: Ingredients, categories, and labels

**Comment by teolemon** [comment]
Solving this issue with a partial taxonomy API pointer will solve a big part of this one: - https://github.com/openfoodfacts/hunger-games/issues/277

Sub-issue: is the partial taxo the right tool for the job ?

**Comment by teolemon** [comment]
- Actually, we have a nice API for that: https://world.openfoodfacts.org/api/v3/product/3017620425035/nutella-ferrero?fields=categories_tags_fr,categories_tags_es
