### ISSUE TITLE
As a user, I'd like to differentiate between keywords and actual content

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/hunger-games#123]
### Description
When using the questions game, sometimes products have a really long ingredients list that isn't easy to read. Example below:
![immagine](https://user-images.githubusercontent.com/12072630/183093929-8aac5933-870e-47e5-8312-c65e6f68de39.png)

### Proposal
Creating a table could benefit readability.

### What would a demo look like
![immagine](https://user-images.githubusercontent.com/12072630/183094746-dbcdfefb-c0e2-4dfa-ad00-d9fe3e1c67a0.png)

**Comment by nobeeakon** [comment]
@VaiTon I feel that they are similar to read, just you have the additional borders, but I may be missing something. ... why do we need the ingredients here?

**Comment by VaiTon** [comment]
I'd do also without borders, but with clear separated sections. For me it's to catch inconsistencies and correct the product

**Comment by alexfauquette** [comment]
The main difference is not the border, it's how the text wraps. With a table below the "ingredients" there is nothing

**Comment by nobeeakon** [comment]
sorry, yeah, I see. Nice, I could do it
