### ISSUE TITLE
Add autosuggest in the logos game

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#129]
### What

- [ ] Invert type and value buttons and add value autosuggest

### Screenshot
<img width="891" alt="image" src="https://user-images.githubusercontent.com/1689815/183304783-0fdf409c-3959-47ba-b5e5-0bfc1cbf9e46.png">

### Why
- Reduce errors

**Comment by sumana2001** [comment]
Could you suggest where we could get the brands, labels etc since not all the data is taxonomized?

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-hungergames/issues/51#issuecomment-1062172047

**Comment by alexfauquette** [comment]
@teolemon It's fixed for labels and category

**Comment by teolemon** [comment]
@alexfauquette for brands, we now have the new openfoodfacts-search endpoint. Opening a separate issue about it
