### ISSUE TITLE
More actionable cards for the logos & labels game

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#136]
### More actionable cards for the logos & labels game
- [ ] This proposal will let users annotate very heterogeneous pages of logos and labels, without having to open separate tabs to annotate each one. As a result, it should make the game faster and more addictive

<img src="https://user-images.githubusercontent.com/1689815/88386693-3c222e80-cdb1-11ea-8ac3-318b458f53fb.png">

- [ ] Fetching 2 top predictions & adding 2 fullfilment buttons next to them for isolated logos
- [ ] Implementing an autocomplete input (in case the prediction are completely off, for isolated logos)

**Comment by alexfauquette** [comment]
Not sure about where we can fetch some value prediction for logo

About the editing. What if we open the editing page in a modal when you click on the pen, such that you can open it, EDT and go back to your main task

**Comment by alexfauquette** [comment]
You now can edit logos without having to move to another page, which is the maximum we can do without an API to get logo predictions

**Comment by teolemon** [comment]
Ok, we can probably close
