### ISSUE TITLE
Make it possible to create a deeplink to filtered view in the insight explorer

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#156]
### What
- Make it possible to create a deeplink to filtered view in the insight explorer
### Why
- Useful to explore insights related to a barcode
### Possible Alternative
- A single barcode view

### Part of
- #254

**Comment by alexfauquette** [comment]
Currently when you click on the barcode it set the barcode in the filters

You mean adding the information in the URL such that `https://hunger.openfoodfacts.org/insights?barcode=3662444002995` directly open the insights table with the correct filter settings?

**Comment by teolemon** [comment]
yep
