### ISSUE TITLE
Add select all/unselect all in the Nutri-Score game

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#166]
### Story
- Add select all/unselect all in the Nutri-Score game

### Part of
- #63

**Comment by alexfauquette** [comment]
Other interactions:

- <kbd>shift</kbd> + click:  select/unselect all the images between the last click and the new clicked image (select/unselect depends on the state of the clicked image)
- <kbd>shift</kbd> + Arrow Right/Left select the next/prev image
