### ISSUE TITLE
No visual feedback that the Labels & Logos annotation query is on-going/completed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#175]
### What
- No visual feedback that the Labels & Logos annotation query is on-going/completed
### Part of
- #85

**Comment by alexfauquette** [comment]
Because the annotation was not sent 🙀

Should be fixed now

**Comment by teolemon** [comment]
The visual feedback (a little spinner or something) might be still important because loading can be slow at times.

**Comment by alexfauquette** [comment]
My bad, I thought you were talking about the feedback when you send data which can also be long

I red "(Labels & Logos) (annotation query)" instead of "(Labels & Logos annotation) query" 😸

**Comment by teolemon** [comment]
save is quick, but loading the next batch can be longer.
