### ISSUE TITLE
Consider extracting useful parts of Hunger Games to our React SDK

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#176]
### What
- We have a https://github.com/openfoodfacts/openfoodfacts-react-native repository that we could rename to openfoodfacts-react, and we could turn that slowly into a dependable package, by extracting relevant and useful parts of Hunger Games, what do you think ?

**Comment by VaiTon** [comment]
Can we consider this superseded by #616 ?

**Comment by teolemon** [comment]
Yes, I guess @VaiTon
