### ISSUE TITLE
Add a login modal on 10th edit

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#177]
### What
- Add a modal prompting/nudging edit on 10th edit

**Comment by teolemon** [comment]
We discussed the opportunity to plug Hunger Games in the newsletter, and there's still resistance. 
- Is there a way we could login directly from Hunger Games ?
- could we trigger login when we click on the user icon ?

**Comment by alexfauquette** [comment]
I do not think we have API route to do the login (maybe I'm wrong)

But we could do a redirect
