### ISSUE TITLE
A missing product or image question, upsets question game

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/hunger-games#203]
### What
If I have a question on a product with an image missing, the page question does not load

### Steps to reproduce the behavior:

1. https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Aorganic (at time of writing)
    question is on a non existing product : 87515114
3. see console, there is a js error

### Screenshots

![Capture d’écran du 2022-09-12 18-08-54](https://user-images.githubusercontent.com/144788/189703492-31b9344e-72e9-4c17-bd3a-6a6e71c38438.png)

![image](https://user-images.githubusercontent.com/144788/189703994-88e0c8d0-cba6-44b8-80f9-2a497d3e5caf.png)

**Comment by alexgarel** [comment]
@alexfauquette this is blocking the game as you can't even skip the question and it turns back if you reload.

**Comment by alexfauquette** [comment]
I think it get fixed by first commit of #208
