### ISSUE TITLE
Logo games: add a load more button

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/hunger-games#212]
When user is sorting logo, some times, he sees there are a good matches, and would like to load more logos to continue adding logo to the batch.

Add a button at the end of the page to load more logo.

Technically it should just submit the same query as the first but asking for more logo, and add logos that are not already displayed.

We should be able to "load more" at least 4 time on the same page (up to 250 logos)

**Comment by alexfauquette** [comment]
Don't hesitate to reopen the issue if you see some problems :)

https://hunger.openfoodfacts.org/logos
![image](https://user-images.githubusercontent.com/45398769/191363851-4e8879f9-b5e1-4353-aff2-68cb127e2e78.png)

**Comment by alexgarel** [comment]
This is really cool @alexfauquette :partying_face:
