### ISSUE TITLE
Introduce popularity ranking for questions about products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#213]
#### What
- After a discussion with @raphael0202 yesterday, it seems that we do have the possibility to rank by scans already
- Introduce the ability for popularity ranking for questions about products to better focus effort

**Comment by alexfauquette** [comment]
It's not what "Sort by popularity" already do?

![image](https://user-images.githubusercontent.com/45398769/191231188-4859b141-e373-401b-bfa8-64ffa5880acd.png)

**Comment by teolemon** [comment]
my brain is not working at all
