### ISSUE TITLE
Logo: Mark non selected logo as not belonging to the label / category etc. ?

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/hunger-games#219]
### Problem
When we review logos to find add annotations.
Most of the time, we can insure that non selected logo do not belong to this category (but the one already annotated).
It would be really useful for example if we want to train a classifier in the future. Because right now we don't have negative example in a secure manner.

### Proposed solution
Propose a checkbox, to auto-mark non selected logos has not belonging to label category.
I think we should also have robotoff supporting it…

### Additional context
Not sure if it's a priority… more like food for thinking :-)

**Comment by alexfauquette** [comment]
I propose to close this issue because now you can select the logos you want, and associate them to the label you want. and if they are not a logo, you can use the new "not a logo" category :)
