### ISSUE TITLE
Show debug info in power mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#221]
### What
- insight id
- generator model
- timestamp

**Comment by alexfauquette** [comment]
## Tech notes

- `robotoff.insightDetail(insight_id)` provide the information from the insight_id associated to the question
- If it comes from logo detector, we can use `robotoff.getLogosImages` and `robotoff.getCroppedImageUrl` to display the logo used

**Comment by raphael0202** [comment]
A few extra information:
- generator model: `predictor` field
- timestamp: `timestamp` field

**Comment by alexfauquette** [comment]
@raphael0202 It seems that `generator model` can also be in `data.model`

And not all the insight based on logo detection includes the cropping bounding box in the `data` object

<details>
<summary>insight example with `data.model="neural"`</summary>

```json
{
  "id": "9cf6b103-6d6d-4131-926f-7eb515ea07fa",
  "barcode": "3527600000010",
  "type": "category",
  "data": {
    "lang": "xx",
    "model": "neural",
    "confidence": 0.5022913813591003
  },
  "timestamp": "2020-02-26T23:53:41.031816",
  "completed_at": null,
  "annotation": null,
  "n_votes": 0,
  "username": null,
  "countries": [
    "en:france"
  ],
  "brands": [],
  "process_after": null,
  "value_tag": "en:coffees",
  "value": null,
  "source_image": null,
  "automatic_processing": false,
  "server_domain": "api.openfoodfacts.org",
  "server_type": "off",
  "unique_scans_n": 2,
  "reserved_barcode": false,
  "predictor": null
}

```
</details>

**Comment by raphael0202** [comment]
`data.model` is a deprecated field and shouldn't be used anymore, so it's a bug from Robotoff side, I will look into this.
