### ISSUE TITLE
[revamp] Create a welcome tour

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#23]
## How to implement the tour

About the implementation aspect: [reactour](https://www.npmjs.com/package/reactour) seems to provide an out of the box component that could be customized later

## What must be highlighted

Maybe @teolemon @alexgarel  or @CharlesNepote will have an opinion on the top

## When do we do the highlight

Long introductions are most of the time boring, so maybe a short one on the first opening and allow a longer one if the user asks for help

**Comment by alexfauquette** [comment]
@sumana2001 what do you think?

**Comment by Amishakumari544** [comment]
@sumana2001 can work on this I will work under her no problem for me.

**Comment by sumana2001** [comment]
Yes sure go ahead @Amishakumari544 ! You can create the steps with dummy data for now, and then we can add the steps according to the requirement. If you need any help, let me know. 
This is what I thought it should look like:
<img width="907" alt="Screenshot 2022-06-24 at 7 28 20 PM" src="https://user-images.githubusercontent.com/63084088/175551129-772ee0b4-5436-464f-84c3-23ce77ba46e5.png">
<img width="907" alt="Screenshot 2022-06-24 at 7 28 28 PM" src="https://user-images.githubusercontent.com/63084088/175551154-727a9817-73dc-4545-aa46-436cf41b36d3.png">

**Comment by Amishakumari544** [comment]
oki @sumana2001
