### ISSUE TITLE
Wrong request when searching Insight without annotation

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/hunger-games#230]
### What

In insight preview, if I choose non annotated in annotation select, I don't get a result.

This is because it send the request 
https://robotoff.openfoodfacts.org/api/v1/insights?annotation=not_annotated&page=1&annotated=0&count=25
which triggers a 400 error on robotoff side.

It should not send the annotation parameter
https://robotoff.openfoodfacts.org/api/v1/insights?page=1&annotated=0&count=25
works.

**Comment by Adnan-Sait** [comment]
I would love to work on this issue.
Could this be assigned to me?
