### ISSUE TITLE
Enlarge the insight image when clicked

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/hunger-games#243]
Often we need to look at the image linked to the insight to see if the prediction is correct. However, the text is sometimes small (see screenshot for example), and we need to enlarge the image to perform the check.
It would be convenient to be able to enlarge the image (all images actually) with a click. 

![Capture d’écran du 2022-10-03 10-58-01](https://user-images.githubusercontent.com/9609923/193539416-fdfe81fd-9dd0-4628-862f-98b849913687.png)

**Comment by alexfauquette** [comment]
Linked to #81
