### ISSUE TITLE
Use i18n for all texts

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#246]
Some texts are not translated, mostly because of my fault. Could be good to clean that.

We are using `"react-i18next"`. To know how to use it, the simplest is maybe to search for a file with `const { t } = useTranslation();`

To add a translation key, you should add it to `src/i18n/common.json` and `src/i18n/en.json`

**Comment by dadolhay** [comment]
@alexfauquette I'd be happy to take this issue, if you're OK with it

**Comment by alexfauquette** [comment]
Thanks for your help :)

About i18n you only need to add keys in `src/i18n/common.json` and `src/i18n/en.json`. A bot will add them later in the other languages

**Comment by dadolhay** [comment]
Thanks for the info!

I have submitted a PR for this issue.

I'm not 100% happy with the "dangerouslySetInnerHTML" stuff, but I did not want to introduce the `Trans` element either (for consistency, and translation readability reasons). According to a (pretty old) i18next ticket, this is how it should be if not using `trans`. I have marked all the places I used it with the GH ticket URL

**Comment by alexfauquette** [comment]
Just saw your message after the PR. Is their a specific reason to do not introduce the `Trans` component (I neither used it, but don't see reason not to)

**Comment by dadolhay** [comment]
There were two reasons
- The project did not use it, and I did not want to diverge from existing patterns
- the numbered injection stuff was not too readable

Since you are OK with it's use, and I found the "alternate method" where the use of named components is possible, I updated the PR.
