### ISSUE TITLE
Make logo search deep-linkable using tags so that we can link from facets on the website, using the Power User Scripthttps://hunger.openfoodfacts.org/logos?logo_tag=en:eu-organic

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#247]
In a perfect world, https://hunger.openfoodfacts.org/logos?logo_tag=en:eu-organic would link to a selection of logos close to organic.

For now, the logo annotation game allows to search neighbours of a specific logo by providing it's `logo_id`:
https://hunger.openfoodfacts.org/logos?logo_id=273955&count=50

We can search logos for label eu_organic from the search interface.
https://hunger.openfoodfacts.org/logos/search/

A dirty solution could be to do the following:

1. If the url parameters contain `logo_tag` sent a query to search logos with this tag
2. Aske for the nearest neighbors of those logos

A second solution is to extend https://hunger.openfoodfacts.org/nutriscore. We could for example add `en:eu_organic` to the nutriscores. For that we would need to get questions generated by logo detection only

**Comment by alexfauquette** [comment]
This experimental page might be a solution to this issue:

https://hunger.openfoodfacts.org/logos/deep-search?type=label&value=en%3Afrench-beef

**Comment by teolemon** [comment]
I believe this is pretty much fixed @alexfauquette @raphael0202 
Can we close ?
