### ISSUE TITLE
Clone the ingredients game from Hunger Games v1 to make a recycling game

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#249]
### What

- [ ] Clone the ingredients game from Hunger Games v1 to make a recycling game

### Code pointers
- The new packaging field which is now live.
  - API-wise, that's an exact replica of the ingredients fields, with the same behaviour, the same ability to OCR the field.
  - instead of ingredients_text_fr, it's packaging_text_fr
- For reference: Related issue for the ingredients game: https://github.com/openfoodfacts/openfoodfacts-hungergames/issues/48
-  Live demo of the ingredients games: https://world.openfoodfacts.org/hunger-game?type=ingredients
   -  https://github.com/openfoodfacts/openfoodfacts-hungergames-react/tree/master/src/Ingredients

### Part of
- https://github.com/openfoodfacts/openfoodfacts-server/issues/6374

**Comment by alexfauquette** [comment]
Not sure if we should go to an text field interface, or is a table as follow would be better

![image](https://user-images.githubusercontent.com/45398769/199342848-ff3b806a-a953-4b5d-b54f-71a5622a616f.png)

**Comment by teolemon** [comment]
This one was working with the old field, without waiting for the new data structure. I guess we can as well project ourselves in the new data structure.

**Comment by teolemon** [comment]
I'm going to close this issue @alexfauquette
