### ISSUE TITLE
Don’t only show annotated logos in /logos/search

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/hunger-games#262]
In https://hunger.openfoodfacts.org/logos/search/, we only show annotated logos. However, this page is really useful to display all logos of a specific product (annotated or not). This way, we can boostrap annotation of logos that are not annotated yet, by selecting products that we know have this logo.

**Comment by alexfauquette** [comment]
I noticed that parameters `annotated=1` is required if you want to filter according to some annotation

- returns not found: https://robotoff.openfoodfacts.org/api/v1/images/logos?value=en:eu-organic&type=label&count=25
- return lot of logos: https://robotoff.openfoodfacts.org/api/v1/images/logos?annotated=1&value=en:eu-organic&type=label&count=25

**Comment by raphael0202** [comment]
Indeed by default `annotated=false`, and there is no way to query logos that are both annotated and not annotated. I'm updating the API so that we don't filter logos based on annotation status.
By the way, I don't know if you know, but Robotoff API documentation can be found here: https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/openfoodfacts/robotoff/master/doc/references/api.yml
This endpoint is not documented, I'm going to document it now :)

**Comment by alexfauquette** [comment]
Nice. maybe you can also ad a link to this doc on the README :)

**Comment by raphael0202** [comment]
By the way I've created a distinct endpoint for logo search (`/images/logos/search` instead of using `/images/logos`), it didn't make any sense to keep it under the same name while the action was different. This is a breaking change so the route should be updated in Hunger Games.
