### ISSUE TITLE
Harmonizing the header color of Hunger Games with the new design

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#273]
### What

- [ ] Harmonizing the header color of Hunger Games with the new design
### Screenshot

<img width="444" alt="image" src="https://user-images.githubusercontent.com/1689815/195395230-d88563a6-5a4c-45f0-8e85-889be3dbe737.png">

### Part of
- #37

**Comment by abhilipsasahoo03** [comment]
Hi @alexfauquette @teolemon I'd like to work on this please?

**Comment by alexfauquette** [comment]
Yes, feel free :)
