### ISSUE TITLE
feat: allowing users to rotate images

### ISSUE THREAD

**Issue by GabrielBeFr** [openfoodfacts/hunger-games#278]
### Problem
In the [HungerGames questions game](https://hunger.openfoodfacts.org/questions), the displayed images of the product are often badly rotated.

### Proposed solutions
Allowing users to rotate the images. 
* It might even be saved in the database to better the quality of the rotation of images.

### Additional context
<img width="688" alt="image" src="https://user-images.githubusercontent.com/112394931/195553041-1d53b8d5-0254-428e-aa15-2736f74c60ec.png">

**Comment by teolemon** [comment]
https://www.youtube.com/watch?v=9hBpF_Zj4OA

**Comment by teolemon** [comment]
- Rotation: we have a server side system to correct rotation based on OCR, but it's not working on the fly, and hasn't been run in ages. In short we could mass autocorrect it.
