### ISSUE TITLE
Logo is not displayed if it's not in nearest neighbor index

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/hunger-games#287]
### Steps to reproduce the behavior:
1. Go to https://hunger.openfoodfacts.org/logos?logo_id=4535845&count=50
2. The logo (https://hunger.openfoodfacts.org/logos/4535845) is not listed in the logo list

We expect the requested logo to always be present, in first position.
This is probably because this logo is new and not indexed on Robotoff ANN side (the index update is still manual). We need to add the requested logo to the list of nearest neighbor logos if it's not returned by the Robotoff ANN API.

**Comment by alexfauquette** [comment]
It comes from an inconsistency in robotoff. Some request includes the logo with distance 0 (himself) and others don't

https://robotoff.openfoodfacts.org/api/v1/ann/731311?count=50
https://robotoff.openfoodfacts.org/api/v1/ann/4535845?count=50

But yes I can add a check to ensure the requested logo id is in the answer with distance 0

**Comment by raphael0202** [comment]
The logo is only returned if it's in the nearest neighbor index, but indeed you're right it should probably be dealt with in Robotoff API directly.
