### ISSUE TITLE
Settings are not accessible when the user is on mobile

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#288]
### What
- Settings are not accessible when the user is on mobile

**Comment by alexfauquette** [comment]
This is handled in the responsive app bar

For now settings are made by an icon on desktop, and commented on mobile. Maybe should be uncommented, and add a property `mobileOnly` to display setting link in mobile menu

https://github.com/openfoodfacts/hunger-games/blob/master/src/components/ResponsiveAppBar.jsx#L35

**Comment by abhilipsasahoo03** [comment]
Completed by issue #312
