### ISSUE TITLE
Some labels don't appear in auto-complete suggestions

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/hunger-games#299]
Example: Health Star rating labels (`en:health-star-rating-1`, `en:health-star-rating-2`,...)

**Comment by alexfauquette** [comment]
Because they are not in https://github.com/openfoodfacts/hunger-games/blob/logo-search/public/data/label.full.json

**Comment by raphael0202** [comment]
Does this file come from here? https://static.openfoodfacts.org/data/taxonomies/labels.full.json
It's the reference file for Robotoff

**Comment by alexfauquette** [comment]
I picked it on robotoff, but a long time ago. The one you linked is more complete.

To generate suggest, you can run the following script after replacing the `.full.json` files
```
node compressSuggestions.js
```
