### ISSUE TITLE
Proposal for new way of mass-annotating logos of a specific value

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/hunger-games#306]
When we want to annotate logos of a specific brand or label, it's not easy to find examples of logos for bootstrapping.

Example: start annotating logos for the brand Bieze (https://world.openfoodfacts.org/brand/bieze)
An effective way to do this is:
- request all products using Product Opener API that have the brand Bieze
- request all logos of the returned barcodes using Robotoff /logos/search route
- display these logos for annotation

The process is a bit different from the current Hunger Games /logos page, as we would need:
- to select type (brand or label)
- enter value (with auto-complete for label)
- logos are displayed. A "load more" button can be used to display additional logos
- Once selected, the user can validate the selection

It would work the same way for labels.

**Comment by alexfauquette** [comment]
Would it be better done once by a script for logos we do not already have annotated ones?

**Comment by alexfauquette** [comment]
Mainly solved by #320. A similar idea is available in #328

Both need some designed refinement before considering this issue closed

**Comment by raphael0202** [comment]
Yes it's done
