### ISSUE TITLE
Product name is not always displayed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#326]
### What
Product name is not always displayed
https://world-fr.openfoodfacts.org/produit/5425035960122/confiture-artisanale-fraises
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1689815/198376742-e49905ea-fa93-40fb-8510-2ea1e4330f3e.png">
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1689815/198376773-04e4562e-8d9f-4d72-bd3b-5e3f399b8ef7.png">

**Comment by alexfauquette** [comment]
Fixed by #354
