### ISSUE TITLE
Dark mode (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#349]
### What
Honestly first attempt is really impressive, here's a tracker of issues as we spot them

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/1689815/199251536-fd2b1963-bbd6-4381-b2d4-007c4b9768c9.png">
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/1689815/199251584-01f531c3-2875-4164-8963-c6677f17b676.png">
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/1689815/199252015-cc38b2ce-fa64-4999-ac77-d201e03d30b7.png">

**Comment by alexfauquette** [comment]
Because mui.com is the best :p

probably some hard-coded colors. Will have a look this week
