### ISSUE TITLE
Create an agribalyse categorization game to validate only Agribalyse focused predictions

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#39]
### What

- [ ] Create an agribalyse categorization game to validate only Agribalyse focused predictions
- [ ] https://github.com/openfoodfacts/openfoodfacts-ai/releases/download/dataset-category-2021-09-15/agribalyse_categories.txt

**Comment by alexfauquette** [comment]
Fo now, the home page display top category/brand/label insights

![image](https://user-images.githubusercontent.com/45398769/190243384-8d1f1010-f220-424c-8d60-6da2f363e030.png)


Will add specific on for agribalise when API will have a specific parameter for that

**Comment by teolemon** [comment]
- From my initial experimentations,  having a full list of categories and labels on a secondary page would be great as well. 
- Validating en:snacks might not be appealing to everyone
-  Agribalyse categories should have much lower counts so any category between 100 and 1000 will more likely trigger Eco-Scores

**Comment by alexfauquette** [comment]
If we want to show only agribalise items, the problem will be that `value_tag` parameters can have only one value.

https://robotoff.openfoodfacts.org/api/v1/questions/unanswered/?type=brand&value_tag=valencia

But I think @alexgarel target is to add a parameter to get only agribalise attributes, so it will be a single line of code to change

**Comment by alexgarel** [comment]
We need to create an issue for that !

**Comment by raphael0202** [comment]
Implemented here: https://github.com/openfoodfacts/robotoff/pull/948
`/unanswered?campaign=agribalyse-category`

**Comment by teolemon** [comment]
We could add the link @alexfauquette mentionned earlier today as a tile in the Eco-Score game ? Also, making sure to rank it by popularity for maximum impact

**Comment by alexfauquette** [comment]
@teolemon I thin this one can be closed, except if you still see an aspect to improve

**Comment by teolemon** [comment]
yes, closing
