### ISSUE TITLE
It would be helpful if we could view an arbitrary barcode in this game (as in type it it, or pass it through the URL)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#396]
### What
- It would be helpful if we could view an arbitrary barcode in this game (as in type it it, or pass it through the URL)

### Mockups
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1689815/206457007-92fb993a-4d62-49fe-965e-099aee23a519.png">

**Comment by alexfauquette** [comment]
The `useBuffer` is ready for that, but maybe better to wait for the API to be ready before improving the game
