### ISSUE TITLE
Bug: nutriscore logo game does not get questtions

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#405]
### What

The nutriscore page shows 0 questions: https://hunger.openfoodfacts.org/nutriscore

But questions exist:

- https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Anutriscore-grade-a&country=&brand=&sorted=false
- https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Anutriscore-grade-b&country=&brand=&sorted=false
- https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Anutriscore-grade-c&country=&brand=&sorted=false
- https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Anutriscore-grade-d&country=&brand=&sorted=false
- https://hunger.openfoodfacts.org/questions?type=label&value_tag=en%3Anutriscore-grade-e&country=&brand=&sorted=false

The  reason is that for [INAO](https://hunger.openfoodfacts.org/inao) game to work I added a filter on `predictor=universal_logo-detactor` But seems nutriscore questions have `predictor=null`

**Comment by raphael0202** [comment]
There is also an object detection model that detects specifically nutriscore, and these predictions with 'null' predictor come from this model.
I've made a fix so that the predictor is now "nutriscore": https://github.com/openfoodfacts/robotoff/commit/3a61b2408b5710b4c81edc25326908a5bfde7ea3

**Comment by raphael0202** [comment]
The fix is now in prod, and I've added `predictor=nutriscore` to these insights in DB.
However it seems you don't fetch any more in nutriscore page nutriscore insights from the universal-logo-detector model?

**Comment by alexfauquette** [comment]
I've replaced the `predictor=universal-logo-detector` with `predictor=nutriscore`. So the new request is:
https://robotoff.openfoodfacts.org/api/v1/questions/random?insight_types=label&value_tag=en:nutriscore-grade-d&predictor=nutriscore&lang=fr&count=50&page=1

I don't know if it works or not, because it seems there is not nutriscore question to answer (see)

https://hunger.openfoodfacts.org/questions?sorted=false&type=label&value_tag=en%3Anutriscore-grade-a
https://hunger.openfoodfacts.org/questions?sorted=false&type=label&value_tag=en%3Anutriscore-grade-b
https://hunger.openfoodfacts.org/questions?sorted=false&type=label&value_tag=en%3Anutriscore-grade-c
https://hunger.openfoodfacts.org/questions?sorted=false&type=label&value_tag=en%3Anutriscore-grade-d
https://hunger.openfoodfacts.org/questions?sorted=false&type=label&value_tag=en%3Anutriscore-grade-e
