### ISSUE TITLE
Add a deep link promo to the logo game when there are no more insights

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#419]
### Problem

- Add a deep link promo to the logo game when there are no more insights on a given label
  - https://hunger.openfoodfacts.org/logos/deep-search?type=label&value=en%3Aresponsible-aquaculture-asc

### Screenshot
![image](https://user-images.githubusercontent.com/1689815/209571963-c0192593-6ece-4320-b35a-b101f0a8b3f6.png)
### Part of
- #85

**Comment by VaiTon** [comment]
Closing as duplicate of https://github.com/openfoodfacts/hunger-games/issues/367
