### ISSUE TITLE
Improve saved filters

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#45]
For now, the home page is far from being interesting. It's empty if you have no saved filters. And if you have some saved filters, they are... factual (to not say uggly)

![image](https://user-images.githubusercontent.com/45398769/177714148-6bb6a92a-1870-435b-ab3e-d68c74d1d5cd.png)

Proposed improvement

Important
- [x] Add a sentence on top to say what is hunger-games
- [x] Add some default cards linking to games
- [x] put an image by default for saved filters

Less important
- [x] set a title by default to saved filters (game 1, game 2, ...)
- [x] allow to edit the filter title

**Comment by teolemon** [comment]
We could have a brand icon, plus potentially a unique "visual" based on the initials of the brands and/or checksum of the brand (in case they have the same initials)
