### ISSUE TITLE
fix: select all in logo game

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#462]
In hunger.openfoodfacts.org/logos when you click "select all", logos that are already annotated are selected. They should be ignored by this button.

**Comment by benbenben2** [comment]
Example, after clicking on "SELECT ALL" button, we can see that already annotated logo is selected:

> ![image](https://user-images.githubusercontent.com/110821832/210875517-32c22f67-73cf-4ad6-be66-28c66231ce9c.png)

**Comment by raphael0202** [comment]
For information, on Robotoff we ignore annotations of already annotated logos, a PUT request should be sent to update information about already annotated logos.
And as a reminder, a /reset route is available to remove annotation on a logo (I'm not sure you saw my previous message).

**Comment by alexfauquette** [comment]
I've seen it it's in my infinite todo 🙈

**Comment by Sudhanva-Nadiger** [comment]
I Have worked on this issue, have a look at it !

# 

![image](https://user-images.githubusercontent.com/93595710/216821709-5c1ce677-a995-4ab0-a81c-42709a9e8a2c.png)

**Comment by alexfauquette** [comment]
@Sudhanva-Nadiger I do not see the PR, did you push your code?

**Comment by Sudhanva-Nadiger** [comment]
yeah I willl do that , was waiting for the approval
