### ISSUE TITLE
Add a `no_logo` type during logo annotation

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/hunger-games#465]
It's really useful to be able to annotate logos that are not in existing types, so that:
- it's not selectable for annotation anymore
- we have a DB of "OTHER" logos to train a logo classifier

We already have a few of these in DB, under the type `no_logo`. No value is expected for this new type.

**Comment by VaiTon** [comment]
Fixed by https://github.com/openfoodfacts/hunger-games/pull/466
