### ISSUE TITLE
Don't warn on empty value

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#480]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1689815/212485895-65b2b1d1-a619-4bbe-b662-b6cb9ab4a721.png">

**Comment by Mount-Blanc** [comment]
I'd like to work on this. Do you want just the warning on empty string removed or empty string and null?

**Comment by alexfauquette** [comment]
You can remove it for both

By the way, if you want, you can join OpenFoodFacts slack (https://slack.openfoodfacts.org/) Especially the #hunger-games channel
