### ISSUE TITLE
No intuitive way to close a modal on mobile

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#483]
### What

- No intuitive way to close a modal on mobile (you have to click outside)
- Can we have a modal control (eg a X) ?

![image](https://user-images.githubusercontent.com/1689815/212879660-cce0e799-563b-491b-85ba-6d7f3a85c94c.png)

**Comment by Sudhanva-Nadiger** [comment]
Can I work on this ?

**Comment by alexfauquette** [comment]
Yes, feel free.

I would add that on mobile the modal could be full screen. It does not make a lot of sens to lose pixels around

**Comment by Sudhanva-Nadiger** [comment]
@alexfauquette have sent [pr](https://github.com/openfoodfacts/hunger-games/pull/495) for this issue. Thanks for the suggestion, done as u said!
