### ISSUE TITLE
Add loading animation when user goes to question route

### ISSUE THREAD

**Issue by Sudhanva-Nadiger** [openfoodfacts/hunger-games#496]
### Problem
When a user goes to the question tab currently it shows only "loading" text.

### Proposed solution
instead we can add a loading animation 

### Mockups
![image](https://user-images.githubusercontent.com/93595710/215157758-4966db2c-86bf-499e-85e9-c1dd1aaa2c83.png)

**Comment by Sudhanva-Nadiger** [comment]
@alexfauquette can I work on this pls ?

**Comment by Sudhanva-Nadiger** [comment]
hey @alexfauquette 

https://user-images.githubusercontent.com/93595710/215251536-ec0503ad-e5c3-474b-88aa-705d2264dc0a.mp4

is this fine ?

**Comment by alexfauquette** [comment]
Yes sound snice, will have a look when I find time

**Comment by Sudhanva-Nadiger** [comment]
I will make pr for it then!

btw can u tell me how I add that sentence to the app localisation?

**Comment by alexfauquette** [comment]
You add it to `i18n/common.json` and `i18n/en.json`
