### ISSUE TITLE
Add a suggestion button to remove the filter value when you arrive at 0 insight left

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#52]
### Story
- Add a suggestion button to remove the filter value when you arrive at 0 insight left
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1689815/178148618-c5053d22-d22c-4c40-8f7a-dd02566e87d3.png">

### Part of
- #37

**Comment by alexfauquette** [comment]
Done in #46

https://deploy-preview-46--warm-cannoli-79bbb2.netlify.app/questions?type=brand&value_tag=toto

**Comment by teolemon** [comment]
closing
