### ISSUE TITLE
Keyboard shortcuts are not working

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/hunger-games#53]
Pressing "o", "k" or "n" does not do anything.

**Comment by sumana2001** [comment]
It is working for me though. Can you try and send a screenshot or video of the error?

https://user-images.githubusercontent.com/63084088/179391528-00f70dfc-b80c-44af-a21e-859d6fdb6e24.mov

**Comment by sumit-158** [comment]
@sumana2001 It does work normally, but after a click anywhere in screen it stops working

https://user-images.githubusercontent.com/96618001/179397690-8bb93ecb-6904-42b7-9c78-6291dbafed82.mp4

**Comment by sumana2001** [comment]
@sumit-158 Okay got it. Thanks for letting me know. I'll send a PR to fix it

**Comment by CharlesNepote** [comment]
And it's not working at all with Firefox browser. Chrome is ok.
I did not test with other browsers.

Thanks @sumana2001.
