### ISSUE TITLE
Text is not contrasting in modals 

### ISSUE THREAD

**Issue by Sudhanva-Nadiger** [openfoodfacts/hunger-games#548]
### Problem
![Screenshot_2023-02-20-17-39-10-12_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/93595710/220102322-576e312e-03a1-426f-aae3-9506856f82d4.jpg)

### Proposed solution
Make it light color probably? 

### Part of
- #37

**Comment by teolemon** [comment]
I cannot reproduce. This is related to customizations on your phone, I believe.
