### ISSUE TITLE
Display the product barcode number, at least for the brand question game

### ISSUE THREAD

**Issue by fabi003** [openfoodfacts/hunger-games#550]
### Problem

If the brand is probably not known to robotoff, in the brand questions game, it would be helpful, to not having first to open the product page in another tab to see it. The reason it should be added to the displayed data fields, is that I have https://hunger.openfoodfacts.org/logos/search open in another tab and search for only the barcode number to see what robotoff knows and annotate the unknown logo.

### Proposed solution

Just display the barcode number, at least for the brand question game.

**Comment by alexfauquette** [comment]
Hi @fabi003 

Sorry for the answer delay, I just discovered your issue while looking for another one 🫣

That's interesting. If someone want to add the feature, it's here , and the barcode is accessible in `question?.barcode`

https://github.com/openfoodfacts/hunger-games/blob/master/src/pages/questions/ProductInformation.jsx/#L88-L118

**Comment by fabi003** [comment]
The direct link to the logo search solves this problem for me.
