### ISSUE TITLE
Add a link to Github issues in the "settings" menu

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/hunger-games#57]
I think it is useful when you want to open an issue or check if it's already open.
Also there are several Hunger Games github repositories and one could create an issue in an old repo.

I don't think it's necessary to create a new menu, putting this into "settings" would be ok.

A version number of the Hunger Game code would be also great but it's probably bigger work.

**Comment by nobeeakon** [comment]
Added the link. Think version number would need more discussion. Related to this, it would be useful to have somewhere an invitation to contribute (eg. link to the github, slack, etc)
