### ISSUE TITLE
Nutri-Score game

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#63]
### What
- Nutri-Score game
- [ ] #62 
- [ ] Make the Nutri-Score game accessible when the DEV mode is enabled
- [ ] Add a counter of the total of Nutri-Scores to validate
- [ ] Add an explanation that you need to select all the valid Nutri-Score A and validate

### Part of 
- #37

**Comment by alexfauquette** [comment]
@teolemon what is the nutri-score game?

**Comment by teolemon** [comment]
![Screenshot_20220730-123028.png](https://user-images.githubusercontent.com/1689815/181906378-6d1ac604-96a9-4cc4-b09c-092b864482e5.png)

**Comment by alexfauquette** [comment]
Ho, yes it was more an experiment. I will share it :)

**Comment by teolemon** [comment]
I added 2 new feat requests
