### ISSUE TITLE
Swap the Microsoft link with the new one

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#635]
### Story
- Swap the Microsoft link with the new one
From https://www.microsoft.com/en-us/p/openfoodfacts/9nblggh0dkqr

to
https://apps.microsoft.com/store/detail/open-food-facts-scan-to-get-nutriscore-ecoscore-and-more/XP8LT18SRPKLRG

### Part of
- #37

**Comment by Mount-Blanc** [comment]
I will work on this .
