### ISSUE TITLE
Bug: white screen in Logos search when clicking on value field first

### ISSUE THREAD

**Issue by DanieliusAsm** [openfoodfacts/hunger-games#688]
### What
White screen when clicking on value field first. You have to click on it first while not having anything in Type selected.

This bug only happens on logos that have no annotation.

### Steps to reproduce the behavior:
1. Go to https://hunger.openfoodfacts.org/logos/search?barcode=4770179104378 (or any other link)
3. Click on value (dont select type leave it blank)
4. Type in something

Im on chrome browser if thats needed.

**Comment by PrateekBhat2** [comment]
can i work on this ?

**Comment by alexfauquette** [comment]
Yes, the solution might be to disable the field

**Comment by PrateekBhat2** [comment]
@DanieliusAsm I am unable to reproduce this even after following the procedure mentioned. Can you elaborate more?

**Comment by alexfauquette** [comment]
Here is the reproduction

after clicking value I'm pressing a letter, leading to the white screen

![image](https://github.com/openfoodfacts/hunger-games/assets/45398769/15b57ae5-3741-4271-bd8e-d7981667d064)

**Comment by PrateekBhat2** [comment]
thanks! will work on it
