### ISSUE TITLE
Add a page for nutrition game

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#71]
To add a page, you need to:

- create a folder with an `index.jsx` returning a React component that will be the nutrition page (see other other pages are made)
- Export this page from [`src/pages/index.js`](https://github.com/openfoodfacts/hunger-games/blob/master/src/pages/index.js)
- Add it to the routing (in `src/App.js`) the route `/nutrition` sounds good

Now you should have access to localhost:3000/nutrition that displays your page

Do not add it to the app bar until the page is finished such that it can not be found by users

----

Could be a good starting point to fetch some products that have a nutrition picture but no data with `getNutritionToFillUrl` method

Display the picture, and add a button to go to the next image

**Comment by Shmigolk** [comment]
I'm going to try it
