### ISSUE TITLE
new game: Ingredient crop

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/hunger-games#714]
The idea would be to create a simple page to crop images with ingredients

![image](https://github.com/openfoodfacts/hunger-games/assets/45398769/c76eefa5-dcca-4f46-9620-31db8496ed98)

Would requires APIs to 

- get image to crop
- get crop estimated by robotoff
- send the crop (does robotoff needs it?)

Open question: how do we store which image has been correctly cropped and then is ready for the future ingredient extraction game?

@raphael0202 is it what you have in mind?

**Comment by raphael0202** [comment]
The idea was not only to select and crop the ingredient image, but also to update the ingredient list. We now have an ingredient detection model in production (demo: https://huggingface.co/spaces/raphael0202/ingredient-extraction?barcode=3800106400226)

If the ingredient list is correct, we're 100% sure about the crop, as cropping coordinates are inferred from the words bounding boxes.

Concerning the input feed of products, we can fetch products that have quality errors/warnings related to ingredients, ordered by descending popularity.

I'm not certain of what the interface should look like, as there are many use cases we want to cover (products without ingredient lists, products with ingredient list but without quality errors), products with more recent ingredient lists detected by the model,...

**Comment by alexfauquette** [comment]
I'm trying the API to reproduce this example:

https://huggingface.co/spaces/raphael0202/ingredient-extraction?barcode=3800106400226

The OCR exists: https://static.openfoodfacts.org/images/products/380/010/640/0226/2.json

But this API call returns Internale server error
https://robotoff.openfoodfacts.org/api/v1/predict/ingredient_list?ocr_url=https://static.openfoodfacts.org/images/products/380/010/640/0226/2.json

**Comment by raphael0202** [comment]
It was not fully deployed on prod, only on staging. I'm finishing the deployment on prod.

**Comment by raphael0202** [comment]
It's working now. To get the result for multiple images, for now you can simply send multiple requests!

**Comment by alexfauquette** [comment]
Yes, perfectly 👍

**Comment by teolemon** [comment]
<img width="384" alt="image" src="https://github.com/openfoodfacts/hunger-games/assets/1689815/0b8b4d68-8778-4e62-ac96-6a2a26686184">
