### ISSUE TITLE
Make the logo dashboard link in Hunger Games menu visible to all users

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/hunger-games#716]
This was hidden by default as this was a test, but I think it would be valuable to display it to all users.
We can also clean the settings, "show logo page" looks like a legacy setting to me (it's always displayed, isn't it)?

### Part of
- #252

**Comment by alexfauquette** [comment]
@raphael0202 

The logo is hiding the firest interface we built: https://hunger.openfoodfacts.org/logos

It can still be useful but it's not the most intuitive one for new users
