### ISSUE TITLE
Images not fully loading/displaying

### ISSUE THREAD

**Issue by nobeeakon** [openfoodfacts/hunger-games#81]
### Story
- when using Firefox (Mac), the images are not properly loaded making it confusing. 

<img width="1318" alt="imagen" src="https://user-images.githubusercontent.com/12853324/181283686-bd6f269a-9cf5-4e63-883c-0f09b1e5a8bd.png">

### Possible causes
 - May be related with the Zoom component from react-medium-image-zoom (as the images are wrapped by that component)
 - If so, an alternative could be to just Material UI capabilities to show a full screen instead of the library

**Comment by alexfauquette** [comment]
It's usefull to be able to zoom on any image, because without zoom, it's hard to read some text. But the main image is also present in the right pannel so having zomm only on right pannel can work

**Comment by CharlesNepote** [comment]
I don't have so much issues with the images at the right. But the left image is never loaded in Firefox.

**Comment by alexfauquette** [comment]
Normally it has been fixed by removing the zoom in the main page
