### ISSUE TITLE
Get a better description for Hunger Games

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#82]
### Story
- Get a better description for Hunger Games

### Screenshot
<img width="678" alt="image" src="https://user-images.githubusercontent.com/1689815/181490927-62e10b66-5c5d-4a3d-9d7e-802837c0e72b.png">

### Part of
- #37

**Comment by alexfauquette** [comment]
File to modify:

https://github.com/openfoodfacts/hunger-games/blob/master/public/index.html#L8:L8

**Comment by alexfauquette** [comment]
What about "Making annotation fast and fun" ?

**Comment by teolemon** [comment]
Answer questions, make food transparency happen ?

**Comment by pratyaksh1610** [comment]
@teolemon @alexfauquette Any thoughts on this ?

"Foodies welcome."
