### ISSUE TITLE
Add a little explanation on how to play the Logos games

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#84]
### Story

- [ ] Add a little explanation on how to play the Logos games
  - [ ] Proposal: "Select all logos that are exactly the same, and give them a name like "en:EU Organic" and a type like "label"."

### Mockup
![image](https://user-images.githubusercontent.com/1689815/181741384-3a87f101-b490-4f0b-82ff-49e63c3d2b15.png)

### Part of

- [ ] #85

**Comment by YashasviChaurasia** [comment]
@alexfauquette @teolemon I would like to work on this issue, Kindly provide me with your approval.

**Comment by nobeeakon** [comment]
> @alexfauquette @teolemon I would like to work on this issue, Kindly provide me with your approval.

Go for it @YashasviChaurasia  :)

**Comment by nobeeakon** [comment]
hey @YashasviChaurasia , please let us know if you need any help (in the [readme](https://github.com/openfoodfacts/hunger-games) you can find the slack.

**Comment by YashasviChaurasia** [comment]
@nobeeakon Just to confirm my method of solving the issue:
I plan on adding a Sentence on the Website page which would talk about the Instructions on how to play the game.
I am planning to add changes to the HTML file of the web page.

Kindly let me know if I am headed in the correct direction

**Comment by YashasviChaurasia** [comment]
@nobeeakon Also, while trying the logo game, I noticed an issue with the website.

The issue is the "Update" button on the logo game page seems unresponsive to the user as it gives no feedback on the button being pressed or the button action being completed.

Should I open a new issue regarding the same in the github repo?

**Comment by nobeeakon** [comment]
hey @YashasviChaurasia , that sounds right. It is about adding a sentence, in this case in jsx but the syntax is similar to html. In the case of the update, it is disabled when no value and type is present so it is kind of expected, thanks anyway for the report.

**Comment by YashasviChaurasia** [comment]
@nobeeakon for the update button,
After filling the value and the type of the images ,the update button is unresponsive as it provides no feedback to user about the button being pressed.

The button works but for the user it appears to be the same as no message or additional event like page refresh occurs after the button is pressed.

By unresponsive I am talking in terms of User Experience not functionality of button.

The unresponsive button can be a bad design for consumers and they might feel the website button is not working even when it does.

I suggest to add a event to the button like refreshing the page or reloading new set of images for the user, or even a text can help the users confirm the button's working 

Thank you

**Comment by YashasviChaurasia** [comment]
@nobeeakon @teolemon @alexfauquette I have a new updated branch with changes ready to be pushed but I am facing an error that says I don't have permission to access the repo.
``` 
ERROR: Permission to openfoodfacts/hunger-games.git denied to YashasviChaurasia.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by YashasviChaurasia** [comment]
@nobeeakon@teolemon @alexfauquette 
 I have created a new local branch with modified code, but I am unable to push it to the repo due to some access right permissions

```
ERROR: Permission to openfoodfacts/hunger-games.git denied to YashasviChaurasia.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by alexfauquette** [comment]
Did you followed [contributing](https://github.com/openfoodfacts/hunger-games/blob/master/CONTRIBUTING.md) steps to manage git?

For open source project you do not have permission to write on the repo. You have to fork it, and push on your local repo

**Comment by YashasviChaurasia** [comment]
Thank you for the guidance.
I have pushed the PR for approval.
Thank you
