### ISSUE TITLE
Add contribution guideline

### ISSUE THREAD

**Issue by nobeeakon** [openfoodfacts/hunger-games#86]
### Task
- Would be useful to have a CONTRIBUTION file that explains the flow for collaborating. Currently it is not a big deal not to have it, but it may be better to have it for the future
- https://github.blog/2012-09-17-contributing-guidelines/

**Comment by alexfauquette** [comment]
The previous repo had one. Maybe just a copy past could do the job. I forget to move it to the new repo

https://github.com/openfoodfacts/openfoodfacts-hungergames/blob/master/CONTRIBUTING.md

**Comment by nobeeakon** [comment]
cool, I can do it
