### ISSUE TITLE
Allow deeplinking to the Category dasbhoard by country

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#879]
### What
- I am fed-up of having Belgian opportunities everytime I open the Eco-Score dashboard
- Allow deeplinking to the Category dashboard by country
- Something like: https://hunger.openfoodfacts.org/eco-score?cc=france
![image](https://github.com/openfoodfacts/hunger-games/assets/1689815/081c3506-f1ab-44ad-a7e1-0a7ad106633e)

**Comment by Gaurav-Verma07** [comment]
Hi @teolemon ,
I've raised a PR regarding this issue.
Please review.
